<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '8f355d6743dc63d22561074544485410',
  'DATABASE_URL' => 'mysql://kztydjpazh49rbc8:zik5f4hqwcsogpyy@ivgz2rnl5rh7sphb.chr7pe7iynqr.eu-west-1.rds.amazonaws.com:3306/jef7f7odukvdpxxq',
  'PROJECT_URL' => 'https://enlienavecvous.org/',
  'PROJECT_ADDR' => 'enlienavecvous.org',
  'API_URL' => '\'https://enlienavecvous.org/api/\'',
  'CORS_ALLOW_ORIGIN' => '^http?://(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$',
  'MAILER_URL' => 'smtp://mail.gandi.net:465?encryption=ssl&auth_mod=login&username=accueil@enlienavecvous.org&password=Gestalthost2020',
  'SENTRY_DSN' => 'https://5f4d0e183ca14d28a8dca9e7092f262f@o384906.ingest.sentry.io/5217090',
  'MAILER_DSN' => 'smtp://mail.gandi.net:465?encryption=ssl&auth_mod=login&username=accueil@enlienavecvous.org&password=Gestalthost2020',
);
